import { Trip, TripStatus } from '@haulhub/shared';

/**
 * Helper function to create complete mock Trip objects for testing
 * Provides all required fields with sensible defaults
 */
export function createMockTrip(overrides: Partial<Trip> = {}): Trip {
  return {
    tripId: 'trip-1',
    dispatcherId: 'dispatcher-1',
    carrierId: 'carrier-1',
    driverId: 'driver-1',
    truckId: 'truck-1',
    truckOwnerId: 'owner-1',
    trailerId: 'trailer-1',
    orderConfirmation: 'ORDER-123',
    scheduledTimestamp: '2024-01-15T10:00:00Z',
    pickupTimestamp: null,
    deliveryTimestamp: null,
    pickupCompany: 'Acme Corp',
    pickupAddress: '123 Main St',
    pickupCity: 'New York',
    pickupState: 'NY',
    pickupZip: '10001',
    pickupPhone: '555-0100',
    pickupNotes: '',
    deliveryCompany: 'Beta Inc',
    deliveryAddress: '456 Oak Ave',
    deliveryCity: 'Boston',
    deliveryState: 'MA',
    deliveryZip: '02101',
    deliveryPhone: '555-0200',
    deliveryNotes: '',
    brokerId: 'broker-1',
    brokerPayment: 1500,
    truckOwnerPayment: 500,
    driverPayment: 800,
    mileageOrder: 200,
    mileageEmpty: 20,
    mileageTotal: 220,
    brokerRate: 7.5,
    driverRate: 4.0,
    truckOwnerRate: 2.5,
    dispatcherRate: 1.0,
    factoryRate: 0,
    orderRate: 7.5,
    orderAverage: 7.5,
    dispatcherPayment: 200,
    brokerAdvance: 0,
    driverAdvance: 0,
    factoryAdvance: 0,
    fuelCost: 100,
    fuelGasAvgCost: 3.5,
    fuelGasAvgGallxMil: 0.15,
    brokerCost: 0,
    factoryCost: 0,
    lumperValue: 0,
    detentionValue: 0,
    orderExpenses: 1600,
    orderRevenue: 1500,
    notes: '',
    orderStatus: TripStatus.Scheduled,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
    ...overrides
  };
}
